### ISSUE TITLE
keep print null in the example

### ISSUE THREAD

**Issue by YanXuHappygela** [joshkatz/r-script#9]
Hi, I cannot recover the results in the example. I have made sure adding R to system path. Is there anything else I can check? Thank you.

**Comment by Corassa** [comment]
Hi, I have the same problem!

**Comment by YanXuHappygela** [comment]
This issues have been solved by starting the server with port 5307: ocpu_start_server(5307)

**Comment by Blackening999** [comment]
Have same issue here. I don't understand how it builds path, but seems like not working at all for me
